### ISSUE TITLE
log forwarding

### ISSUE THREAD

**Issue by prayagupa** [nihil-os/james-joyce#2]
java

```bash
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm"

sudo yum -y localinstall jdk-8u60-linux-x64.rpm
sudo alternatives --config java

export JAVA_HOME=/usr/java/jdk1.8.0_60/
export PATH=$PATH:$JAVA_HOME/bin
```

elasticsearch
---------------

```bash
#wget https://artifacts.elastic.co/downloads/logstash/logstash-5.2.2.tar.gz
#tar zxvf logstash-5.2.2.tar.gz 

wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.tar.gz
elasticsearch-5.1.1/bin/elasticsearch
```
indexstorage.service

forwarder-logging
---

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html

```
logging.level: warning
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/log-forwarder/
  name: myforwarder.log
  keepfiles: 7
```
