### ISSUE TITLE
alerting

### ISSUE THREAD

**Issue by prayagupa** [nihil-os/james-joyce#3]
```
GET some_team-prod-microservice-2017.05.11/_search
{
  "query": {
    "term": {
      "level.keyword": "ERROR"
    }
  }
}
```

using elastalert
--

https://github.com/Yelp/elastalert/issues/1042#issuecomment-296752622

http://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html

```yaml
filter:
   - query_string:
      query: "level.keyword:ERROR"
```
